package com.test.dao;

import com.test.model.user;
import com.test.model.userExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface userMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jia
     *
     * @mbg.generated
     */
    long countByExample(userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jia
     *
     * @mbg.generated
     */
    int deleteByExample(userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jia
     *
     * @mbg.generated
     */
    int insert(user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jia
     *
     * @mbg.generated
     */
    int insertSelective(user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jia
     *
     * @mbg.generated
     */
    List<user> selectByExample(userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jia
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") user record, @Param("example") userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jia
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") user record, @Param("example") userExample example);
}